/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Issue } from "./Issue";
import { IssueCountArgs } from "./IssueCountArgs";
import { IssueFindManyArgs } from "./IssueFindManyArgs";
import { IssueFindUniqueArgs } from "./IssueFindUniqueArgs";
import { CreateIssueArgs } from "./CreateIssueArgs";
import { UpdateIssueArgs } from "./UpdateIssueArgs";
import { DeleteIssueArgs } from "./DeleteIssueArgs";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { Repository } from "../../repository/base/Repository";
import { IssueService } from "../issue.service";
@graphql.Resolver(() => Issue)
export class IssueResolverBase {
  constructor(protected readonly service: IssueService) {}

  async _issuesMeta(
    @graphql.Args() args: IssueCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Issue])
  async issues(@graphql.Args() args: IssueFindManyArgs): Promise<Issue[]> {
    return this.service.issues(args);
  }

  @graphql.Query(() => Issue, { nullable: true })
  async issue(
    @graphql.Args() args: IssueFindUniqueArgs
  ): Promise<Issue | null> {
    const result = await this.service.issue(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Issue)
  async createIssue(@graphql.Args() args: CreateIssueArgs): Promise<Issue> {
    return await this.service.createIssue({
      ...args,
      data: {
        ...args.data,

        repository: args.data.repository
          ? {
              connect: args.data.repository,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Issue)
  async updateIssue(
    @graphql.Args() args: UpdateIssueArgs
  ): Promise<Issue | null> {
    try {
      return await this.service.updateIssue({
        ...args,
        data: {
          ...args.data,

          repository: args.data.repository
            ? {
                connect: args.data.repository,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Issue)
  async deleteIssue(
    @graphql.Args() args: DeleteIssueArgs
  ): Promise<Issue | null> {
    try {
      return await this.service.deleteIssue(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Comment], { name: "comments" })
  async findComments(
    @graphql.Parent() parent: Issue,
    @graphql.Args() args: CommentFindManyArgs
  ): Promise<Comment[]> {
    const results = await this.service.findComments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Repository, {
    nullable: true,
    name: "repository",
  })
  async getRepository(
    @graphql.Parent() parent: Issue
  ): Promise<Repository | null> {
    const result = await this.service.getRepository(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
