/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { IssueService } from "../issue.service";
import { IssueCreateInput } from "./IssueCreateInput";
import { Issue } from "./Issue";
import { IssueFindManyArgs } from "./IssueFindManyArgs";
import { IssueWhereUniqueInput } from "./IssueWhereUniqueInput";
import { IssueUpdateInput } from "./IssueUpdateInput";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { CommentWhereUniqueInput } from "../../comment/base/CommentWhereUniqueInput";

export class IssueControllerBase {
  constructor(protected readonly service: IssueService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Issue })
  async createIssue(@common.Body() data: IssueCreateInput): Promise<Issue> {
    return await this.service.createIssue({
      data: {
        ...data,

        repository: data.repository
          ? {
              connect: data.repository,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        status: true,

        repository: {
          select: {
            id: true,
          },
        },

        assignee: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Issue] })
  @ApiNestedQuery(IssueFindManyArgs)
  async issues(@common.Req() request: Request): Promise<Issue[]> {
    const args = plainToClass(IssueFindManyArgs, request.query);
    return this.service.issues({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        status: true,

        repository: {
          select: {
            id: true,
          },
        },

        assignee: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Issue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async issue(
    @common.Param() params: IssueWhereUniqueInput
  ): Promise<Issue | null> {
    const result = await this.service.issue({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        title: true,
        description: true,
        status: true,

        repository: {
          select: {
            id: true,
          },
        },

        assignee: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Issue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateIssue(
    @common.Param() params: IssueWhereUniqueInput,
    @common.Body() data: IssueUpdateInput
  ): Promise<Issue | null> {
    try {
      return await this.service.updateIssue({
        where: params,
        data: {
          ...data,

          repository: data.repository
            ? {
                connect: data.repository,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          status: true,

          repository: {
            select: {
              id: true,
            },
          },

          assignee: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Issue })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteIssue(
    @common.Param() params: IssueWhereUniqueInput
  ): Promise<Issue | null> {
    try {
      return await this.service.deleteIssue({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          title: true,
          description: true,
          status: true,

          repository: {
            select: {
              id: true,
            },
          },

          assignee: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/comments")
  @ApiNestedQuery(CommentFindManyArgs)
  async findComments(
    @common.Req() request: Request,
    @common.Param() params: IssueWhereUniqueInput
  ): Promise<Comment[]> {
    const query = plainToClass(CommentFindManyArgs, request.query);
    const results = await this.service.findComments(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        content: true,
        author: true,

        issue: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/comments")
  async connectComments(
    @common.Param() params: IssueWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        connect: body,
      },
    };
    await this.service.updateIssue({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/comments")
  async updateComments(
    @common.Param() params: IssueWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        set: body,
      },
    };
    await this.service.updateIssue({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/comments")
  async disconnectComments(
    @common.Param() params: IssueWhereUniqueInput,
    @common.Body() body: CommentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      comments: {
        disconnect: body,
      },
    };
    await this.service.updateIssue({
      where: params,
      data,
      select: { id: true },
    });
  }
}
